name: PremiumEconomias
version: '1.0.0'
main: com.premiumsetups.premiumeconomias.PremiumEconomias
authors: [ Bletzzi ]
description: Plugin de economias da PremiumSetups
website: premiumsetups.com
softdepend: [PlaceHolderAPI]